name: CI

# We run CI on every push
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

# Automatically cancel running workflows when there's a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: read

jobs:
  typecheck:
    name: Typechecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - run: pnpm install
      - run: pnpm typecheck
